### ISSUE TITLE
Crash at runtime due to 'SyntaxError'

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/ethercalc_ynh#7]
Installation goes fine. The service starts. After first access to the web page, I get a 502 Bad gateway, because the ethercalc process crashes. The logs say :

```
Please connect to: http://ynh:8000/
Starting backend using webworker-threads
Falling back to vm.CreateContext backend

/var/www/ethercalc/node_modules/ethercalc/node_modules/nodemailer/lib/nodemailer.js:3
const Mailer = require('./mailer');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.include (/var/www/ethercalc/node_modules/ethercalc/emailer.js:13:18)
    at Object.context.include (/var/www/ethercalc/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.include (/var/www/ethercalc/node_modules/ethercalc/sc.js:214:20)
    at Object.context.include (/var/www/ethercalc/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.include (/var/www/ethercalc/node_modules/ethercalc/main.js:17:15)
    at Object.context.include (/var/www/ethercalc/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:581:26)
    at Object.<anonymous> (/var/www/ethercalc/node_modules/ethercalc/app.js:58:17)
    at Object.zappa.app (/var/www/ethercalc/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:875:10)
    at zappa.run (/var/www/ethercalc/node_modules/ethercalc/node_modules/zappajs/lib/zappa.js:1024:18)
    at Object.<anonymous> (/var/www/ethercalc/node_modules/ethercalc/app.js:49:21)
    at Object.<anonymous> (/var/www/ethercalc/node_modules/ethercalc/app.js:60:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/ethercalc/node_modules/ethercalc/bin/ethercalc:7:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

This might very well be an incompatibility between the nodejs-legacy version and the current ethercalc code...

**Comment by julienmalik** [comment]
The reference docker file uses a nodejs 4.4 :
https://github.com/audreyt/ethercalc/blob/master/Dockerfile

**Comment by TortuePatate** [comment]
Same problem here : installation goes fine but I get a 502 nginx bad gateway when launching the app.

**Comment by Jaxom99** [comment]
I concurr, I have the same problem on my Rpi3-Debian8 yunohost v2.7.2 this day.
Is anybody up to fix this ? Ethercalc is such a practical service !

**Comment by e-jim** [comment]
Hey, I saw this remark on [ethercalc's github ](https://github.com/audreyt/ethercalc/#installation):

> Nodejs older than 6.0
> downgrade Nodemailer to v2.7.2

So I did this: 
```bash
sudo su ethercalc
cd node_modules/ethercalc/
npm remove nodemailer
npm install nodemailer@2.7.2

```
And it works! (although I got a warning that the lib is deprecated, so we should still investigate going to nodejs6 and that nvm thingy).

**Comment by decentral1se** [comment]
Yes, this is because the old installation script used an incorrect version of Nodejs.

I've resolved this with https://github.com/YunoHost-Apps/ethercalc_ynh/pull/15 using 4.8.7.

Please note, there is no working upgrade script right now, so you'd have to re-install ...

I'm going to close this off.
